### ISSUE TITLE
Add standard navigation links to the default page footer.

### ISSUE THREAD

**Issue by ari5av** [ari5av/dw#20]
The header has been removed from the create page, so now there's no way to navigate the site besides the browser back button.  Figure out what navigation links need to go in the footer, they may as well go in the default one to show up on every page.

**Comment by breakf5** [comment]
I'm honestly, not sure what you mean by this? Why don't we keep the header
on all other pages and just make a new page template for /create? Seems
much easier then globally disabling the header. Maybe I don't get it but
I'm very confused.

**Comment by breakf5** [comment]
We should put the navigation menu back up, people don't like not having the navigation menu
