### ISSUE TITLE
In code, restrict template keys to 30 characters or fewer.

### ISSUE THREAD

**Issue by ari5av** [ari5av/dw#25]
The database currently has template keys at VARCHAR(30), but there's no validation for it.

Frontend side, in grab_variables():
After the match, strip out any values greater than 30 characters from the variables array.

API side:
When asking for template values for a key>30, don't return anything for that key, because it should be treated as a non-variable.  Ideally this shouldn't happen, but we need the preventative measure.

**Comment by breakf5** [comment]
could you make VARCHAR(60) or any other number without messing things up?

**Comment by breakf5** [comment]
Can you make it varchar(60) or any othe

**Comment by ari5av** [comment]
I can change it to 60, yes.  Is that the final string length we're going for?

**Comment by breakf5** [comment]
Yes, 60 should be the final. Just long enough not too long

**Comment by ari5av** [comment]
60 it is, on its way soon...

**Comment by ari5av** [comment]
Done, and added a tooltip next to "Phrase:" that explains everything.  It works even if you try to break it though.
