### ISSUE TITLE
Need a visual cue to display while AJAX requests are loading.

### ISSUE THREAD

**Issue by ari5av** [ari5av/dw#6]
Currently the bottleneck seems to be network speed, but there's still a very slight lag.

We should do one or more of these:
- Change the mouse cursor
- Display a spinning wheel
- Entirely disable the control we're loading data into

We should probably not disable the control, because TBH typing in it does still work, and as you type it re-renders, so if it loads while you're typing, it still works fine.  I recommend the spinning wheel.

**Comment by breakf5** [comment]
Now that AJAX loads are so much quicker, is this really necessary? Is it worth the time at this point?
