### ISSUE TITLE
Add professions to the list

### ISSUE THREAD

**Issue by ari5av** [ari5av/dw#9]
1) School Psychologist 
SPSY

2) School Speech Pathologist
(we should probably change the selection for SLP on registration to be "Medical Speech Pathologist"
(So they'll be two options "School Speech Pathologist" & "Medical Speech Pathologist"
SST for school speech therapist

3) Blank - A totally Blank database
BLNK

4) Special Education/IEP/Teacher
SE

5) Chiropractor
Chiro

6) Audiology
AUD

7) Dietitian
RD (for registered dietitian)

8) Behavioral Health/Social Work
BHSW

9) Respiratory Therapy
RT

10) Physician/Nurse Practitioner/Physician's Assistant
MED 

11) Nursing/ MDS Nurse
NSG

**Comment by breakf5** [comment]
ABA Therapist

**Comment by breakf5** [comment]
Visual Impairment

**Comment by breakf5** [comment]
Wheelchair and Orthotics

**Comment by ari5av** [comment]
Done.
